// Generated by tsbindgen - Architecture
// Namespace: System.Xml.Linq
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IComparer_1, IEnumerable_1, IEqualityComparer_1 } from '../System.Collections.Generic/internal/index.js';
import type { IComparer, IEqualityComparer } from '../System.Collections/internal/index.js';
import type { Stream, TextReader, TextWriter } from '../System.IO/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { Task, Task_1 } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { XmlSchema } from '../System.Xml.Schema/internal/index.js';
import type { IXmlSerializable } from '../System.Xml.Serialization/internal/index.js';
import type { IXmlLineInfo, XmlNodeType, XmlReader, XmlWriter } from '../System.Xml/internal/index.js';
import type { Boolean as ClrBoolean, Enum, EventArgs, EventHandler_1, IComparable, IConvertible, IEquatable_1, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { Extensions$instance as Extensions } from './internal/index.js';
export { XAttribute as XAttribute } from './internal/index.js';
export { XCData as XCData } from './internal/index.js';
export { XComment as XComment } from './internal/index.js';
export { XContainer as XContainer } from './internal/index.js';
export { XDeclaration as XDeclaration } from './internal/index.js';
export { XDocument as XDocument } from './internal/index.js';
export { XDocumentType as XDocumentType } from './internal/index.js';
export { XElement as XElement } from './internal/index.js';
export { XObjectChange as XObjectChange } from './internal/index.js';
export { LoadOptions as LoadOptions } from './internal/index.js';
export { SaveOptions as SaveOptions } from './internal/index.js';
export { ReaderOptions as ReaderOptions } from './internal/index.js';
export { XName as XName } from './internal/index.js';
export { XNamespace as XNamespace } from './internal/index.js';
export { XNode as XNode } from './internal/index.js';
export { XNodeDocumentOrderComparer as XNodeDocumentOrderComparer } from './internal/index.js';
export { XNodeEqualityComparer as XNodeEqualityComparer } from './internal/index.js';
export { XObject as XObject } from './internal/index.js';
export { XObjectChangeEventArgs as XObjectChangeEventArgs } from './internal/index.js';
export { XProcessingInstruction as XProcessingInstruction } from './internal/index.js';
export { XStreamingElement as XStreamingElement } from './internal/index.js';
export { XText as XText } from './internal/index.js';
