// Generated by tsbindgen - Architecture
// Namespace: System.Text.Json.Nodes
// Assembly: System.Text.Json

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Collections_Generic_Internal from "../../System.Collections.Generic/internal/index.js";
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IList_1, KeyValuePair_2 } from "../../System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { IEnumerable, IEnumerator } from "../../System.Collections/internal/index.js";
import type { Stream } from "../../System.IO/internal/index.js";
import type { JsonTypeInfo_1 } from "../../System.Text.Json.Serialization.Metadata/internal/index.js";
import type { JsonDocumentOptions, JsonElement, JsonSerializerOptions, JsonValueKind, Utf8JsonReader, Utf8JsonWriter } from "../../System.Text.Json/internal/index.js";
import type { Task_1 } from "../../System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "../../System.Threading/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Char, DateTime, DateTimeOffset, Decimal, Double, Func_2, Guid, Int16, Int32, Int64, Nullable_1, Object as ClrObject, ReadOnlySpan_1, SByte, Single, String as ClrString, Type, UInt16, UInt32, UInt64, ValueType, Void } from "../../System/internal/index.js";

export interface JsonNodeOptions$instance {
    PropertyNameCaseInsensitive: boolean;
}


export const JsonNodeOptions: {
    new(): JsonNodeOptions;
};


export type JsonNodeOptions = JsonNodeOptions$instance;

export interface JsonArray$instance extends JsonNode {
    readonly Count: int;
    Add<T>(value: T): void;
    Add(item: JsonNode): void;
    Clear(): void;
    Contains(item: JsonNode): boolean;
    GetEnumerator(): IEnumerator_1<JsonNode | undefined>;
    GetValues<T>(): IEnumerable_1<T>;
    IndexOf(item: JsonNode): int;
    Insert(index: int, item: JsonNode): void;
    Remove(item: JsonNode): boolean;
    RemoveAll(match: Func_2<JsonNode, System_Internal.Boolean>): int;
    RemoveAt(index: int): void;
    RemoveRange(index: int, count: int): void;
    WriteTo(writer: Utf8JsonWriter, options?: JsonSerializerOptions): void;
}


export const JsonArray: {
    new(options: Nullable_1<JsonNodeOptions>): JsonArray;
    new(options: JsonNodeOptions, items: JsonNode[]): JsonArray;
    new(options: JsonNodeOptions, items: ReadOnlySpan_1<JsonNode>): JsonArray;
    new(items: JsonNode[]): JsonArray;
    new(items: ReadOnlySpan_1<JsonNode>): JsonArray;
    Create(element: JsonElement, options?: Nullable_1<JsonNodeOptions>): JsonArray | undefined;
};


export interface __JsonArray$views {
    As_ICollection_1(): System_Collections_Generic_Internal.ICollection_1$instance<JsonNode>;
    As_IEnumerable_1(): System_Collections_Generic_Internal.IEnumerable_1$instance<JsonNode>;
    As_IList_1(): System_Collections_Generic_Internal.IList_1$instance<JsonNode>;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
}

export type JsonArray = JsonArray$instance & __JsonArray$views;


export interface JsonNode$instance {
    readonly Options: Nullable_1<JsonNodeOptions>;
    readonly Parent: JsonNode;
    readonly Root: JsonNode;
    AsArray(): JsonArray;
    AsObject(): JsonObject;
    AsValue(): JsonValue;
    DeepClone(): JsonNode;
    get_Item(index: int): JsonNode;
    get_Item(propertyName: string): JsonNode;
    GetElementIndex(): int;
    GetPath(): string;
    GetPropertyName(): string;
    GetValue<T>(): T;
    GetValueKind(): JsonValueKind;
    ReplaceWith<T>(value: T): void;
    set_Item(index: int, value: JsonNode | undefined): void;
    set_Item(propertyName: string, value: JsonNode | undefined): void;
    ToJsonString(options?: JsonSerializerOptions): string;
    ToString(): string;
    WriteTo(writer: Utf8JsonWriter, options?: JsonSerializerOptions): void;
}


export const JsonNode: {
    DeepEquals(node1: JsonNode, node2: JsonNode): boolean;
    Parse(utf8Json: Stream, nodeOptions?: Nullable_1<JsonNodeOptions>, documentOptions?: JsonDocumentOptions): JsonNode | undefined;
    Parse(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, nodeOptions?: Nullable_1<JsonNodeOptions>, documentOptions?: JsonDocumentOptions): JsonNode | undefined;
    Parse(json: string, nodeOptions?: Nullable_1<JsonNodeOptions>, documentOptions?: JsonDocumentOptions): JsonNode | undefined;
    Parse(reader: Utf8JsonReader, nodeOptions?: Nullable_1<JsonNodeOptions>): JsonNode | undefined;
    ParseAsync(utf8Json: Stream, nodeOptions?: Nullable_1<JsonNodeOptions>, documentOptions?: JsonDocumentOptions, cancellationToken?: CancellationToken): Task_1<JsonNode | undefined>;
};


export type JsonNode = JsonNode$instance;

export interface JsonObject$instance extends JsonNode {
    readonly Count: int;
    Add(propertyName: string, value: JsonNode): void;
    Add(property: KeyValuePair_2<System_Internal.String, JsonNode>): void;
    Clear(): void;
    ContainsKey(propertyName: string): boolean;
    GetAt(index: int): KeyValuePair_2<System_Internal.String, JsonNode>;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, JsonNode>>;
    IndexOf(propertyName: string): int;
    Insert(index: int, propertyName: string, value: JsonNode): void;
    Remove(propertyName: string): boolean;
    RemoveAt(index: int): void;
    SetAt(index: int, propertyName: string, value: JsonNode): void;
    SetAt(index: int, value: JsonNode): void;
    TryAdd(propertyName: string, value: JsonNode): boolean;
    TryAdd(propertyName: string, value: JsonNode, index: int): boolean;
    TryGetPropertyValue(propertyName: string, jsonNode: JsonNode): boolean;
    TryGetPropertyValue(propertyName: string, jsonNode: JsonNode, index: int): boolean;
    WriteTo(writer: Utf8JsonWriter, options?: JsonSerializerOptions): void;
}


export const JsonObject: {
    new(options: Nullable_1<JsonNodeOptions>): JsonObject;
    new(properties: IEnumerable_1<KeyValuePair_2<System_Internal.String, JsonNode>>, options: Nullable_1<JsonNodeOptions>): JsonObject;
    Create(element: JsonElement, options?: Nullable_1<JsonNodeOptions>): JsonObject | undefined;
};


export interface __JsonObject$views {
    As_ICollection_1(): System_Collections_Generic_Internal.ICollection_1$instance<KeyValuePair_2<System_Internal.String, JsonNode>>;
    As_IDictionary_2(): System_Collections_Generic_Internal.IDictionary_2$instance<System_Internal.String, JsonNode>;
    As_IEnumerable_1(): System_Collections_Generic_Internal.IEnumerable_1$instance<KeyValuePair_2<System_Internal.String, JsonNode>>;
    As_IList_1(): System_Collections_Generic_Internal.IList_1$instance<KeyValuePair_2<System_Internal.String, JsonNode>>;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
}

export type JsonObject = JsonObject$instance & __JsonObject$views;


export interface JsonValue$instance extends JsonNode {
    TryGetValue<T>(value: T): boolean;
}


export const JsonValue: {
    Create(value: boolean, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: byte, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: char, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: DateTime, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: DateTimeOffset, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: decimal, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: double, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: Guid, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: short, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: int, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: long, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: Nullable_1<System_Internal.Boolean>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Byte>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Char>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<DateTime>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<DateTimeOffset>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Decimal>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Double>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<Guid>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Int16>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Int32>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Int64>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.SByte>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.Single>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<JsonElement>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.UInt16>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.UInt32>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: Nullable_1<System_Internal.UInt64>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: sbyte, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: float, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: string, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: JsonElement, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create(value: ushort, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: uint, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create(value: ulong, options?: Nullable_1<JsonNodeOptions>): JsonValue;
    Create<T>(value: T, jsonTypeInfo: JsonTypeInfo_1<T>, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
    Create<T>(value: T, options?: Nullable_1<JsonNodeOptions>): JsonValue | undefined;
};


export type JsonValue = JsonValue$instance;

