// Generated by tsbindgen - Architecture
// Namespace: System.Security.Cryptography.X509Certificates
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { SafeX509ChainHandle } from '../Microsoft.Win32.SafeHandles/internal/index.js';
import type { IEnumerable_1, IEnumerator_1 } from '../System.Collections.Generic/internal/index.js';
import type { Collection_1 } from '../System.Collections.ObjectModel/internal/index.js';
import type { CollectionBase, ICollection, IDictionary, IEnumerable, IEnumerator, IList } from '../System.Collections/internal/index.js';
import type { UniversalTagNumber } from '../System.Formats.Asn1/internal/index.js';
import type { IPAddress } from '../System.Net/internal/index.js';
import type { BigInteger } from '../System.Numerics/internal/index.js';
import type { MethodBase } from '../System.Reflection/internal/index.js';
import type { IDeserializationCallback, ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { AsnEncodedData, AsymmetricAlgorithm, CompositeMLDsa, CryptographicException, DSA, ECDiffieHellman, ECDsa, HashAlgorithmName, MLDsa, MLKem, Oid, OidCollection, PbeParameters, RSA, RSASignaturePadding, SlhDsa } from '../System.Security.Cryptography/internal/index.js';
import type { SecureString } from '../System.Security/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Char, DateTime, DateTimeOffset, Enum, Exception, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, IntPtr, ISpanFormattable, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Span_1, String as ClrString, TimeSpan, Type, TypeCode, Uri, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { Pkcs12LoaderLimits as Pkcs12LoaderLimits } from './internal/index.js';
export { Pkcs12LoadLimitExceededException as Pkcs12LoadLimitExceededException } from './internal/index.js';
export { X509CertificateLoader$instance as X509CertificateLoader } from './internal/index.js';
export { CertificateRequest as CertificateRequest } from './internal/index.js';
export { CertificateRequestLoadOptions as CertificateRequestLoadOptions } from './internal/index.js';
export { CertificateRevocationListBuilder as CertificateRevocationListBuilder } from './internal/index.js';
export { DSACertificateExtensions$instance as DSACertificateExtensions } from './internal/index.js';
export { ECDsaCertificateExtensions$instance as ECDsaCertificateExtensions } from './internal/index.js';
export { OpenFlags as OpenFlags } from './internal/index.js';
export { Pkcs12ExportPbeParameters as Pkcs12ExportPbeParameters } from './internal/index.js';
export { PublicKey as PublicKey } from './internal/index.js';
export { RSACertificateExtensions$instance as RSACertificateExtensions } from './internal/index.js';
export { StoreLocation as StoreLocation } from './internal/index.js';
export { StoreName as StoreName } from './internal/index.js';
export { SubjectAlternativeNameBuilder as SubjectAlternativeNameBuilder } from './internal/index.js';
export { X500DistinguishedName as X500DistinguishedName } from './internal/index.js';
export { X500DistinguishedNameBuilder as X500DistinguishedNameBuilder } from './internal/index.js';
export { X500DistinguishedNameFlags as X500DistinguishedNameFlags } from './internal/index.js';
export { X500RelativeDistinguishedName as X500RelativeDistinguishedName } from './internal/index.js';
export { X509AuthorityInformationAccessExtension as X509AuthorityInformationAccessExtension } from './internal/index.js';
export { X509AuthorityKeyIdentifierExtension as X509AuthorityKeyIdentifierExtension } from './internal/index.js';
export { X509BasicConstraintsExtension as X509BasicConstraintsExtension } from './internal/index.js';
export { X509Certificate as X509Certificate } from './internal/index.js';
export { X509Certificate2 as X509Certificate2 } from './internal/index.js';
export { X509Certificate2Collection as X509Certificate2Collection } from './internal/index.js';
export { X509Certificate2Enumerator as X509Certificate2Enumerator } from './internal/index.js';
export { X509CertificateCollection as X509CertificateCollection } from './internal/index.js';
export { X509CertificateCollection_X509CertificateEnumerator as X509CertificateCollection_X509CertificateEnumerator } from './internal/index.js';
export { X509Chain as X509Chain } from './internal/index.js';
export { X509ChainElement as X509ChainElement } from './internal/index.js';
export { X509ChainElementCollection as X509ChainElementCollection } from './internal/index.js';
export { X509ChainElementEnumerator as X509ChainElementEnumerator } from './internal/index.js';
export { X509ChainPolicy as X509ChainPolicy } from './internal/index.js';
export { X509ChainStatus as X509ChainStatus } from './internal/index.js';
export { X509ChainStatusFlags as X509ChainStatusFlags } from './internal/index.js';
export { X509ChainTrustMode as X509ChainTrustMode } from './internal/index.js';
export { X509ContentType as X509ContentType } from './internal/index.js';
export { X509EnhancedKeyUsageExtension as X509EnhancedKeyUsageExtension } from './internal/index.js';
export { X509Extension as X509Extension } from './internal/index.js';
export { X509ExtensionCollection as X509ExtensionCollection } from './internal/index.js';
export { X509ExtensionEnumerator as X509ExtensionEnumerator } from './internal/index.js';
export { X509FindType as X509FindType } from './internal/index.js';
export { X509IncludeOption as X509IncludeOption } from './internal/index.js';
export { X509KeyStorageFlags as X509KeyStorageFlags } from './internal/index.js';
export { X509KeyUsageExtension as X509KeyUsageExtension } from './internal/index.js';
export { X509KeyUsageFlags as X509KeyUsageFlags } from './internal/index.js';
export { X509NameType as X509NameType } from './internal/index.js';
export { X509RevocationFlag as X509RevocationFlag } from './internal/index.js';
export { X509RevocationMode as X509RevocationMode } from './internal/index.js';
export { X509RevocationReason as X509RevocationReason } from './internal/index.js';
export { X509SignatureGenerator as X509SignatureGenerator } from './internal/index.js';
export { X509Store as X509Store } from './internal/index.js';
export { X509SubjectAlternativeNameExtension as X509SubjectAlternativeNameExtension } from './internal/index.js';
export { X509SubjectKeyIdentifierExtension as X509SubjectKeyIdentifierExtension } from './internal/index.js';
export { X509SubjectKeyIdentifierHashAlgorithm as X509SubjectKeyIdentifierHashAlgorithm } from './internal/index.js';
export { X509VerificationFlags as X509VerificationFlags } from './internal/index.js';
