// Generated by tsbindgen - Architecture
// Namespace: System.Collections.Concurrent
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IEqualityComparer_1, IList_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, KeyValuePair_2 } from '../System.Collections.Generic/internal/index.js';
import type { ICollection, IDictionary, IDictionaryEnumerator, IEnumerable, IEnumerator } from '../System.Collections/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Enum, Func_2, Func_3, Func_4, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, TimeSpan, Tuple_2, Type, TypeCode, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { BlockingCollection_1 as BlockingCollection_1 } from './internal/index.js';
export { BlockingCollection_1 as BlockingCollection } from './internal/index.js';
export { ConcurrentBag_1 as ConcurrentBag_1 } from './internal/index.js';
export { ConcurrentBag_1 as ConcurrentBag } from './internal/index.js';
export { ConcurrentDictionary_2 as ConcurrentDictionary_2 } from './internal/index.js';
export { ConcurrentDictionary_2 as ConcurrentDictionary } from './internal/index.js';
export { ConcurrentDictionary_2_AlternateLookup_1 as ConcurrentDictionary_2_AlternateLookup_1 } from './internal/index.js';
export { ConcurrentStack_1 as ConcurrentStack_1 } from './internal/index.js';
export { ConcurrentStack_1 as ConcurrentStack } from './internal/index.js';
export { OrderablePartitioner_1 as OrderablePartitioner_1 } from './internal/index.js';
export { OrderablePartitioner_1 as OrderablePartitioner } from './internal/index.js';
export { Partitioner_1 as Partitioner_1 } from './internal/index.js';
export { Partitioner_1 as Partitioner } from './internal/index.js';
export { EnumerablePartitionerOptions as EnumerablePartitionerOptions } from './internal/index.js';
export { Partitioner$instance as Partitioner_0 } from './internal/index.js';
export { ConcurrentQueue_1 as ConcurrentQueue_1 } from './internal/index.js';
export { ConcurrentQueue_1 as ConcurrentQueue } from './internal/index.js';
export type IProducerConsumerCollection_1<T> = Internal.IProducerConsumerCollection_1<T>;
export type IProducerConsumerCollection<T> = Internal.IProducerConsumerCollection_1<T>;
