// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.InteropServices.JavaScript
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary } from '../System.Collections/internal/index.js';
import type { MethodBase, MethodInfo } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { Task, Task_1 } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Action, Action_1, Action_2, Action_3, ArraySegment_1, AsyncCallback, Attribute, Boolean as ClrBoolean, Byte, Char, DateTime, DateTimeOffset, Delegate, Double, Exception, Func_1, Func_2, Func_3, Func_4, IAsyncResult, ICloneable, IDisposable, Int16, Int32, Int64, IntPtr, MulticastDelegate, Nullable_1, Object as ClrObject, ReadOnlySpan_1, Single, Span_1, String as ClrString, Type, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { JSImportAttribute as JSImportAttribute } from './internal/index.js';
export { JSExportAttribute as JSExportAttribute } from './internal/index.js';
export { JSMarshalAsAttribute_1 as JSMarshalAsAttribute_1 } from './internal/index.js';
export { JSMarshalAsAttribute_1 as JSMarshalAsAttribute } from './internal/index.js';
export { JSType as JSType } from './internal/index.js';
export { JSObject as JSObject } from './internal/index.js';
export { JSException as JSException } from './internal/index.js';
export { JSHost$instance as JSHost } from './internal/index.js';
export { JSFunctionBinding as JSFunctionBinding } from './internal/index.js';
export { JSMarshalerType as JSMarshalerType } from './internal/index.js';
export { JSMarshalerArgument as JSMarshalerArgument } from './internal/index.js';
export { JSType_Void as JSType_Void } from './internal/index.js';
export { JSType_Discard as JSType_Discard } from './internal/index.js';
export { JSType_Boolean as JSType_Boolean } from './internal/index.js';
export { JSType_Number as JSType_Number } from './internal/index.js';
export { JSType_BigInt as JSType_BigInt } from './internal/index.js';
export { JSType_Date as JSType_Date } from './internal/index.js';
export { JSType_String as JSType_String } from './internal/index.js';
export { JSType_Object as JSType_Object } from './internal/index.js';
export { JSType_Error as JSType_Error } from './internal/index.js';
export { JSType_MemoryView as JSType_MemoryView } from './internal/index.js';
export { JSType_Array_1 as JSType_Array_1 } from './internal/index.js';
export { JSType_Array_1 as JSType_Array } from './internal/index.js';
export { JSType_Promise_1 as JSType_Promise_1 } from './internal/index.js';
export { JSType_Promise_1 as JSType_Promise } from './internal/index.js';
export { JSType_Function as JSType_Function_0 } from './internal/index.js';
export { JSType_Function_1 as JSType_Function_1 } from './internal/index.js';
export { JSType_Function_1 as JSType_Function } from './internal/index.js';
export { JSType_Function_2 as JSType_Function_2 } from './internal/index.js';
export { JSType_Function_3 as JSType_Function_3 } from './internal/index.js';
export { JSType_Function_4 as JSType_Function_4 } from './internal/index.js';
export { JSType_Any as JSType_Any } from './internal/index.js';
export type JSMarshalerArgument_ArgumentToManagedCallback_1<T> = Internal.JSMarshalerArgument_ArgumentToManagedCallback_1<T>;
export type JSMarshalerArgument_ArgumentToManagedCallback<T> = Internal.JSMarshalerArgument_ArgumentToManagedCallback_1<T>;
export type JSMarshalerArgument_ArgumentToJSCallback_1<T> = Internal.JSMarshalerArgument_ArgumentToJSCallback_1<T>;
export type JSMarshalerArgument_ArgumentToJSCallback<T> = Internal.JSMarshalerArgument_ArgumentToJSCallback_1<T>;
