// Generated by tsbindgen - Architecture
// Namespace: System.CodeDom.Compiler
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { TextWriter } from '../System.IO/internal/index.js';
import type { Encoding, StringBuilder } from '../System.Text/internal/index.js';
import type { Task, ValueTask } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Attribute, Boolean as ClrBoolean, Char, Decimal, Double, IAsyncDisposable, IDisposable, IFormatProvider, Int32, Int64, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Single, String as ClrString, Type, UInt32, UInt64, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { GeneratedCodeAttribute as GeneratedCodeAttribute } from './internal/index.js';
export { IndentedTextWriter as IndentedTextWriter } from './internal/index.js';
