// Generated by tsbindgen - Architecture
// Namespace: System.ComponentModel.DataAnnotations.Schema
// Assembly: System.ComponentModel.Annotations

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "../../System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode } from "../../System/internal/index.js";

export enum DatabaseGeneratedOption {
    None = 0,
    Identity = 1,
    Computed = 2
}


export interface ColumnAttribute$instance extends Attribute {
    readonly Name: string;
    Order: int;
    TypeName: string;
}


export const ColumnAttribute: {
    new(): ColumnAttribute$instance;
    new(name: string): ColumnAttribute$instance;
};


export type ColumnAttribute = ColumnAttribute$instance;

export interface ComplexTypeAttribute$instance extends Attribute {
}


export const ComplexTypeAttribute: {
    new(): ComplexTypeAttribute$instance;
};


export type ComplexTypeAttribute = ComplexTypeAttribute$instance;

export interface DatabaseGeneratedAttribute$instance extends Attribute {
    readonly DatabaseGeneratedOption: DatabaseGeneratedOption;
}


export const DatabaseGeneratedAttribute: {
    new(databaseGeneratedOption: DatabaseGeneratedOption): DatabaseGeneratedAttribute$instance;
};


export type DatabaseGeneratedAttribute = DatabaseGeneratedAttribute$instance;

export interface ForeignKeyAttribute$instance extends Attribute {
    readonly Name: string;
}


export const ForeignKeyAttribute: {
    new(name: string): ForeignKeyAttribute$instance;
};


export type ForeignKeyAttribute = ForeignKeyAttribute$instance;

export interface InversePropertyAttribute$instance extends Attribute {
    readonly Property: string;
}


export const InversePropertyAttribute: {
    new(property: string): InversePropertyAttribute$instance;
};


export type InversePropertyAttribute = InversePropertyAttribute$instance;

export interface NotMappedAttribute$instance extends Attribute {
}


export const NotMappedAttribute: {
    new(): NotMappedAttribute$instance;
};


export type NotMappedAttribute = NotMappedAttribute$instance;

export interface TableAttribute$instance extends Attribute {
    readonly Name: string;
    Schema: string;
}


export const TableAttribute: {
    new(name: string): TableAttribute$instance;
};


export type TableAttribute = TableAttribute$instance;

