// Generated by tsbindgen - Architecture
// Namespace: System.Buffers.Binary
// Assembly: System.Private.CoreLib

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import support types from @tsonic/types
import type { ptr } from "@tsonic/types";

// Import types from other namespaces
import * as System_Internal from "../../System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Double, Half, Int128, Int16, Int32, Int64, IntPtr, Object as ClrObject, ReadOnlySpan_1, SByte, Single, Span_1, String as ClrString, Type, UInt128, UInt16, UInt32, UInt64, UIntPtr, Void } from "../../System/internal/index.js";

export abstract class BinaryPrimitives$instance {
    static ReadDoubleBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): double;
    static ReadDoubleLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): double;
    static ReadHalfBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): half;
    static ReadHalfLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): half;
    static ReadInt128BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): int128;
    static ReadInt128LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): int128;
    static ReadInt16BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): short;
    static ReadInt16LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): short;
    static ReadInt32BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): int;
    static ReadInt32LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): int;
    static ReadInt64BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): long;
    static ReadInt64LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): long;
    static ReadIntPtrBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): nint;
    static ReadIntPtrLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): nint;
    static ReadSingleBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): float;
    static ReadSingleLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): float;
    static ReadUInt128BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): uint128;
    static ReadUInt128LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): uint128;
    static ReadUInt16BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): ushort;
    static ReadUInt16LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): ushort;
    static ReadUInt32BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): uint;
    static ReadUInt32LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): uint;
    static ReadUInt64BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): ulong;
    static ReadUInt64LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): ulong;
    static ReadUIntPtrBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>): nuint;
    static ReadUIntPtrLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>): nuint;
    static ReverseEndianness(value: byte): byte;
    static ReverseEndianness(value: int128): int128;
    static ReverseEndianness(value: short): short;
    static ReverseEndianness(value: int): int;
    static ReverseEndianness(value: long): long;
    static ReverseEndianness(value: nint): nint;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.Int128>, destination: Span_1<System_Internal.Int128>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.Int16>, destination: Span_1<System_Internal.Int16>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.Int32>, destination: Span_1<System_Internal.Int32>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.Int64>, destination: Span_1<System_Internal.Int64>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.IntPtr>, destination: Span_1<System_Internal.IntPtr>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.UInt128>, destination: Span_1<System_Internal.UInt128>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.UInt16>, destination: Span_1<System_Internal.UInt16>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.UInt32>, destination: Span_1<System_Internal.UInt32>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.UInt64>, destination: Span_1<System_Internal.UInt64>): void;
    static ReverseEndianness(source: ReadOnlySpan_1<System_Internal.UIntPtr>, destination: Span_1<System_Internal.UIntPtr>): void;
    static ReverseEndianness(value: sbyte): sbyte;
    static ReverseEndianness(value: uint128): uint128;
    static ReverseEndianness(value: ushort): ushort;
    static ReverseEndianness(value: uint): uint;
    static ReverseEndianness(value: ulong): ulong;
    static ReverseEndianness(value: nuint): nuint;
    static TryReadDoubleBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: double): boolean;
    static TryReadDoubleLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: double): boolean;
    static TryReadHalfBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: half): boolean;
    static TryReadHalfLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: half): boolean;
    static TryReadInt128BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: int128): boolean;
    static TryReadInt128LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: int128): boolean;
    static TryReadInt16BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: short): boolean;
    static TryReadInt16LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: short): boolean;
    static TryReadInt32BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: int): boolean;
    static TryReadInt32LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: int): boolean;
    static TryReadInt64BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: long): boolean;
    static TryReadInt64LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: long): boolean;
    static TryReadIntPtrBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: nint): boolean;
    static TryReadIntPtrLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: nint): boolean;
    static TryReadSingleBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: float): boolean;
    static TryReadSingleLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: float): boolean;
    static TryReadUInt128BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: uint128): boolean;
    static TryReadUInt128LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: uint128): boolean;
    static TryReadUInt16BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: ushort): boolean;
    static TryReadUInt16LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: ushort): boolean;
    static TryReadUInt32BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: uint): boolean;
    static TryReadUInt32LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: uint): boolean;
    static TryReadUInt64BigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: ulong): boolean;
    static TryReadUInt64LittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: ulong): boolean;
    static TryReadUIntPtrBigEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: nuint): boolean;
    static TryReadUIntPtrLittleEndian(source: ReadOnlySpan_1<System_Internal.Byte>, value: nuint): boolean;
    static TryWriteDoubleBigEndian(destination: Span_1<System_Internal.Byte>, value: double): boolean;
    static TryWriteDoubleLittleEndian(destination: Span_1<System_Internal.Byte>, value: double): boolean;
    static TryWriteHalfBigEndian(destination: Span_1<System_Internal.Byte>, value: half): boolean;
    static TryWriteHalfLittleEndian(destination: Span_1<System_Internal.Byte>, value: half): boolean;
    static TryWriteInt128BigEndian(destination: Span_1<System_Internal.Byte>, value: int128): boolean;
    static TryWriteInt128LittleEndian(destination: Span_1<System_Internal.Byte>, value: int128): boolean;
    static TryWriteInt16BigEndian(destination: Span_1<System_Internal.Byte>, value: short): boolean;
    static TryWriteInt16LittleEndian(destination: Span_1<System_Internal.Byte>, value: short): boolean;
    static TryWriteInt32BigEndian(destination: Span_1<System_Internal.Byte>, value: int): boolean;
    static TryWriteInt32LittleEndian(destination: Span_1<System_Internal.Byte>, value: int): boolean;
    static TryWriteInt64BigEndian(destination: Span_1<System_Internal.Byte>, value: long): boolean;
    static TryWriteInt64LittleEndian(destination: Span_1<System_Internal.Byte>, value: long): boolean;
    static TryWriteIntPtrBigEndian(destination: Span_1<System_Internal.Byte>, value: nint): boolean;
    static TryWriteIntPtrLittleEndian(destination: Span_1<System_Internal.Byte>, value: nint): boolean;
    static TryWriteSingleBigEndian(destination: Span_1<System_Internal.Byte>, value: float): boolean;
    static TryWriteSingleLittleEndian(destination: Span_1<System_Internal.Byte>, value: float): boolean;
    static TryWriteUInt128BigEndian(destination: Span_1<System_Internal.Byte>, value: uint128): boolean;
    static TryWriteUInt128LittleEndian(destination: Span_1<System_Internal.Byte>, value: uint128): boolean;
    static TryWriteUInt16BigEndian(destination: Span_1<System_Internal.Byte>, value: ushort): boolean;
    static TryWriteUInt16LittleEndian(destination: Span_1<System_Internal.Byte>, value: ushort): boolean;
    static TryWriteUInt32BigEndian(destination: Span_1<System_Internal.Byte>, value: uint): boolean;
    static TryWriteUInt32LittleEndian(destination: Span_1<System_Internal.Byte>, value: uint): boolean;
    static TryWriteUInt64BigEndian(destination: Span_1<System_Internal.Byte>, value: ulong): boolean;
    static TryWriteUInt64LittleEndian(destination: Span_1<System_Internal.Byte>, value: ulong): boolean;
    static TryWriteUIntPtrBigEndian(destination: Span_1<System_Internal.Byte>, value: nuint): boolean;
    static TryWriteUIntPtrLittleEndian(destination: Span_1<System_Internal.Byte>, value: nuint): boolean;
    static WriteDoubleBigEndian(destination: Span_1<System_Internal.Byte>, value: double): void;
    static WriteDoubleLittleEndian(destination: Span_1<System_Internal.Byte>, value: double): void;
    static WriteHalfBigEndian(destination: Span_1<System_Internal.Byte>, value: half): void;
    static WriteHalfLittleEndian(destination: Span_1<System_Internal.Byte>, value: half): void;
    static WriteInt128BigEndian(destination: Span_1<System_Internal.Byte>, value: int128): void;
    static WriteInt128LittleEndian(destination: Span_1<System_Internal.Byte>, value: int128): void;
    static WriteInt16BigEndian(destination: Span_1<System_Internal.Byte>, value: short): void;
    static WriteInt16LittleEndian(destination: Span_1<System_Internal.Byte>, value: short): void;
    static WriteInt32BigEndian(destination: Span_1<System_Internal.Byte>, value: int): void;
    static WriteInt32LittleEndian(destination: Span_1<System_Internal.Byte>, value: int): void;
    static WriteInt64BigEndian(destination: Span_1<System_Internal.Byte>, value: long): void;
    static WriteInt64LittleEndian(destination: Span_1<System_Internal.Byte>, value: long): void;
    static WriteIntPtrBigEndian(destination: Span_1<System_Internal.Byte>, value: nint): void;
    static WriteIntPtrLittleEndian(destination: Span_1<System_Internal.Byte>, value: nint): void;
    static WriteSingleBigEndian(destination: Span_1<System_Internal.Byte>, value: float): void;
    static WriteSingleLittleEndian(destination: Span_1<System_Internal.Byte>, value: float): void;
    static WriteUInt128BigEndian(destination: Span_1<System_Internal.Byte>, value: uint128): void;
    static WriteUInt128LittleEndian(destination: Span_1<System_Internal.Byte>, value: uint128): void;
    static WriteUInt16BigEndian(destination: Span_1<System_Internal.Byte>, value: ushort): void;
    static WriteUInt16LittleEndian(destination: Span_1<System_Internal.Byte>, value: ushort): void;
    static WriteUInt32BigEndian(destination: Span_1<System_Internal.Byte>, value: uint): void;
    static WriteUInt32LittleEndian(destination: Span_1<System_Internal.Byte>, value: uint): void;
    static WriteUInt64BigEndian(destination: Span_1<System_Internal.Byte>, value: ulong): void;
    static WriteUInt64LittleEndian(destination: Span_1<System_Internal.Byte>, value: ulong): void;
    static WriteUIntPtrBigEndian(destination: Span_1<System_Internal.Byte>, value: nuint): void;
    static WriteUIntPtrLittleEndian(destination: Span_1<System_Internal.Byte>, value: nuint): void;
}


export type BinaryPrimitives = BinaryPrimitives$instance;

