// Generated by tsbindgen - Architecture
// Namespace: System.Security.Cryptography.Xml
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Security.Cryptography.Xml/internal/index.js';

// Cross-namespace type imports for constraints
import type { Collection_1 } from './System.Collections.ObjectModel/internal/index.js';
import type { ArrayList, Hashtable, ICollection, IDictionary, IEnumerable, IEnumerator, IList } from './System.Collections/internal/index.js';
import type { Stream } from './System.IO/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { X509Certificate, X509Certificate2, X509IncludeOption } from './System.Security.Cryptography.X509Certificates/internal/index.js';
import type { AsymmetricAlgorithm, CipherMode, DSA, HashAlgorithm, KeyedHashAlgorithm, PaddingMode, RSA, SymmetricAlgorithm } from './System.Security.Cryptography/internal/index.js';
import type { Evidence } from './System.Security.Policy/internal/index.js';
import type { Encoding } from './System.Text/internal/index.js';
import type { XmlDocument, XmlElement, XmlException, XmlNodeList, XmlResolver } from './System.Xml/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Exception, Func_2, Int32, Object as ClrObject, String as ClrString, Type, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { X509IssuerSerial as X509IssuerSerial } from './System.Security.Cryptography.Xml/internal/index.js';
export { CipherData as CipherData } from './System.Security.Cryptography.Xml/internal/index.js';
export { CipherReference as CipherReference } from './System.Security.Cryptography.Xml/internal/index.js';
export { CryptoSignedXmlRecursionException as CryptoSignedXmlRecursionException } from './System.Security.Cryptography.Xml/internal/index.js';
export { DataObject as DataObject } from './System.Security.Cryptography.Xml/internal/index.js';
export { DataReference as DataReference } from './System.Security.Cryptography.Xml/internal/index.js';
export { DSAKeyValue as DSAKeyValue } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptedData as EncryptedData } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptedKey as EncryptedKey } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptedReference as EncryptedReference } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptedType as EncryptedType } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptedXml as EncryptedXml } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptionMethod as EncryptionMethod } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptionProperty as EncryptionProperty } from './System.Security.Cryptography.Xml/internal/index.js';
export { EncryptionPropertyCollection as EncryptionPropertyCollection } from './System.Security.Cryptography.Xml/internal/index.js';
export type IRelDecryptor = Internal.IRelDecryptor;
export { KeyInfo as KeyInfo } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyInfoClause as KeyInfoClause } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyInfoEncryptedKey as KeyInfoEncryptedKey } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyInfoName as KeyInfoName } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyInfoNode as KeyInfoNode } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyInfoRetrievalMethod as KeyInfoRetrievalMethod } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyInfoX509Data as KeyInfoX509Data } from './System.Security.Cryptography.Xml/internal/index.js';
export { KeyReference as KeyReference } from './System.Security.Cryptography.Xml/internal/index.js';
export { Reference as Reference } from './System.Security.Cryptography.Xml/internal/index.js';
export { ReferenceList as ReferenceList } from './System.Security.Cryptography.Xml/internal/index.js';
export { RSAKeyValue as RSAKeyValue } from './System.Security.Cryptography.Xml/internal/index.js';
export { Signature as Signature } from './System.Security.Cryptography.Xml/internal/index.js';
export { SignedInfo as SignedInfo } from './System.Security.Cryptography.Xml/internal/index.js';
export { SignedXml as SignedXml } from './System.Security.Cryptography.Xml/internal/index.js';
export { Transform as Transform } from './System.Security.Cryptography.Xml/internal/index.js';
export { TransformChain as TransformChain } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDecryptionTransform as XmlDecryptionTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigBase64Transform as XmlDsigBase64Transform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigC14NTransform as XmlDsigC14NTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigC14NWithCommentsTransform as XmlDsigC14NWithCommentsTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigEnvelopedSignatureTransform as XmlDsigEnvelopedSignatureTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigExcC14NTransform as XmlDsigExcC14NTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigExcC14NWithCommentsTransform as XmlDsigExcC14NWithCommentsTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigXPathTransform as XmlDsigXPathTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlDsigXsltTransform as XmlDsigXsltTransform } from './System.Security.Cryptography.Xml/internal/index.js';
export { XmlLicenseTransform as XmlLicenseTransform } from './System.Security.Cryptography.Xml/internal/index.js';
