// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Versioning
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { Attribute, Boolean as ClrBoolean, Enum, IComparable, IConvertible, IEquatable_1, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, Version } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { ComponentGuaranteesAttribute as ComponentGuaranteesAttribute } from './internal/index.js';
export { ComponentGuaranteesOptions as ComponentGuaranteesOptions } from './internal/index.js';
export { FrameworkName as FrameworkName } from './internal/index.js';
export { OSPlatformAttribute as OSPlatformAttribute } from './internal/index.js';
export { TargetPlatformAttribute as TargetPlatformAttribute } from './internal/index.js';
export { SupportedOSPlatformAttribute as SupportedOSPlatformAttribute } from './internal/index.js';
export { UnsupportedOSPlatformAttribute as UnsupportedOSPlatformAttribute } from './internal/index.js';
export { ObsoletedOSPlatformAttribute as ObsoletedOSPlatformAttribute } from './internal/index.js';
export { SupportedOSPlatformGuardAttribute as SupportedOSPlatformGuardAttribute } from './internal/index.js';
export { UnsupportedOSPlatformGuardAttribute as UnsupportedOSPlatformGuardAttribute } from './internal/index.js';
export { RequiresPreviewFeaturesAttribute as RequiresPreviewFeaturesAttribute } from './internal/index.js';
export { ResourceConsumptionAttribute as ResourceConsumptionAttribute } from './internal/index.js';
export { ResourceExposureAttribute as ResourceExposureAttribute } from './internal/index.js';
export { ResourceScope as ResourceScope } from './internal/index.js';
export { TargetFrameworkAttribute as TargetFrameworkAttribute } from './internal/index.js';
export { VersioningHelper$instance as VersioningHelper } from './internal/index.js';
