// Generated by tsbindgen - Architecture
// Namespace: System.Xml.Xsl
// Assembly: System.Private.Xml

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IDictionary_2 } from "../../System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { IDictionary, IEnumerable, IEnumerator } from "../../System.Collections/internal/index.js";
import type { Stream, TextWriter } from "../../System.IO/internal/index.js";
import type { MethodBase, MethodInfo } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { IXPathNavigable, XPathNavigator, XPathResultType } from "../../System.Xml.XPath/internal/index.js";
import * as System_Xml_Internal from "../../System.Xml/internal/index.js";
import type { IXmlNamespaceResolver, XmlNamespaceManager, XmlNamespaceScope, XmlNameTable, XmlReader, XmlResolver, XmlWriter, XmlWriterSettings } from "../../System.Xml/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { AsyncCallback, Boolean as ClrBoolean, Byte, Delegate, EventArgs, Exception, IAsyncResult, ICloneable, Int32, IntPtr, MulticastDelegate, Object as ClrObject, String as ClrString, SystemException, Type, Void } from "../../System/internal/index.js";

export type XsltMessageEncounteredEventHandler = (sender: unknown, e: XsltMessageEncounteredEventArgs) => void;


export interface IXsltContextFunction$instance {
    readonly Minargs: int;
    readonly Maxargs: int;
    readonly ReturnType: XPathResultType;
    readonly ArgTypes: XPathResultType[];
    Invoke(xsltContext: XsltContext, args: unknown[], docContext: XPathNavigator): unknown;
}


export type IXsltContextFunction = IXsltContextFunction$instance;

export interface IXsltContextVariable$instance {
    readonly IsLocal: boolean;
    readonly IsParam: boolean;
    readonly VariableType: XPathResultType;
    Evaluate(xsltContext: XsltContext): unknown;
}


export type IXsltContextVariable = IXsltContextVariable$instance;

export interface XslCompiledTransform$instance {
    readonly OutputSettings: XmlWriterSettings | undefined;
    Load(stylesheet: XmlReader): void;
    Load(stylesheet: XmlReader, settings: XsltSettings | undefined, stylesheetResolver: XmlResolver | undefined): void;
    Load(stylesheet: IXPathNavigable): void;
    Load(stylesheet: IXPathNavigable, settings: XsltSettings | undefined, stylesheetResolver: XmlResolver | undefined): void;
    Load(stylesheetUri: string): void;
    Load(stylesheetUri: string, settings: XsltSettings | undefined, stylesheetResolver: XmlResolver | undefined): void;
    Load(compiledStylesheet: Type): void;
    Load(executeMethod: MethodInfo, queryData: byte[], earlyBoundTypes: Type[] | undefined): void;
    Transform(input: IXPathNavigable, results: XmlWriter): void;
    Transform(input: IXPathNavigable, arguments: XsltArgumentList | undefined, results: XmlWriter): void;
    Transform(input: IXPathNavigable, arguments: XsltArgumentList | undefined, results: TextWriter): void;
    Transform(input: IXPathNavigable, arguments: XsltArgumentList | undefined, results: Stream): void;
    Transform(input: XmlReader, results: XmlWriter): void;
    Transform(input: XmlReader, arguments: XsltArgumentList | undefined, results: XmlWriter): void;
    Transform(input: XmlReader, arguments: XsltArgumentList | undefined, results: TextWriter): void;
    Transform(input: XmlReader, arguments: XsltArgumentList | undefined, results: Stream): void;
    Transform(inputUri: string, results: XmlWriter): void;
    Transform(inputUri: string, arguments: XsltArgumentList | undefined, results: XmlWriter): void;
    Transform(inputUri: string, arguments: XsltArgumentList | undefined, results: TextWriter): void;
    Transform(inputUri: string, arguments: XsltArgumentList | undefined, results: Stream): void;
    Transform(inputUri: string, resultsFile: string): void;
    Transform(input: XmlReader, arguments: XsltArgumentList | undefined, results: XmlWriter, documentResolver: XmlResolver | undefined): void;
    Transform(input: IXPathNavigable, arguments: XsltArgumentList | undefined, results: XmlWriter, documentResolver: XmlResolver | undefined): void;
}


export const XslCompiledTransform: {
    new(): XslCompiledTransform;
    new(enableDebug: boolean): XslCompiledTransform;
};


export type XslCompiledTransform = XslCompiledTransform$instance;

export interface XsltArgumentList$instance {
    AddExtensionObject(namespaceUri: string, extension: unknown): void;
    AddParam(name: string, namespaceUri: string, parameter: unknown): void;
    Clear(): void;
    GetExtensionObject(namespaceUri: string): unknown | undefined;
    GetParam(name: string, namespaceUri: string): unknown | undefined;
    RemoveExtensionObject(namespaceUri: string): unknown | undefined;
    RemoveParam(name: string, namespaceUri: string): unknown | undefined;
}


export const XsltArgumentList: {
    new(): XsltArgumentList;
};


export type XsltArgumentList = XsltArgumentList$instance;

export interface XsltCompileException$instance extends XsltException$instance {
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export const XsltCompileException: {
    new(): XsltCompileException;
    new(message: string): XsltCompileException;
    new(message: string, innerException: Exception): XsltCompileException;
    new(inner: Exception, sourceUri: string, lineNumber: int, linePosition: int): XsltCompileException;
};


export interface __XsltCompileException$views {
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type XsltCompileException = XsltCompileException$instance & __XsltCompileException$views;


export interface XsltContext$instance extends XmlNamespaceManager {
    readonly Whitespace: boolean;
    CompareDocument(baseUri: string, nextbaseUri: string): int;
    GetEnumerator(): IEnumerator;
    GetNamespacesInScope(scope: XmlNamespaceScope): IDictionary_2<System_Internal.String, System_Internal.String>;
    LookupNamespace(prefix: string): string | undefined;
    PreserveWhitespace(node: XPathNavigator): boolean;
    ResolveFunction(prefix: string, name: string, ArgTypes: XPathResultType[]): IXsltContextFunction;
    ResolveVariable(prefix: string, name: string): IXsltContextVariable;
}


export const XsltContext: {
};


export interface __XsltContext$views {
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IXmlNamespaceResolver(): System_Xml_Internal.IXmlNamespaceResolver$instance;
}

export type XsltContext = XsltContext$instance & __XsltContext$views;


export interface XsltException$instance extends SystemException {
    readonly LineNumber: int;
    readonly LinePosition: int;
    readonly Message: string;
    readonly SourceUri: string | undefined;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export const XsltException: {
    new(): XsltException;
    new(message: string): XsltException;
    new(message: string, innerException: Exception | undefined): XsltException;
};


export interface __XsltException$views {
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type XsltException = XsltException$instance & __XsltException$views;


export interface XsltMessageEncounteredEventArgs$instance extends EventArgs {
    readonly Message: string;
}


export const XsltMessageEncounteredEventArgs: {
};


export type XsltMessageEncounteredEventArgs = XsltMessageEncounteredEventArgs$instance;

export interface XslTransform$instance {
    XmlResolver: XmlResolver;
    Load(stylesheet: XmlReader): void;
    Load(stylesheet: XmlReader, resolver: XmlResolver | undefined): void;
    Load(stylesheet: IXPathNavigable): void;
    Load(stylesheet: IXPathNavigable, resolver: XmlResolver | undefined): void;
    Load(stylesheet: XPathNavigator): void;
    Load(stylesheet: XPathNavigator, resolver: XmlResolver | undefined): void;
    Load(url: string): void;
    Load(url: string, resolver: XmlResolver | undefined): void;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, resolver: XmlResolver | undefined): XmlReader;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined): XmlReader;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, output: XmlWriter, resolver: XmlResolver | undefined): void;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, output: XmlWriter): void;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, output: Stream, resolver: XmlResolver | undefined): void;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, output: Stream): void;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, output: TextWriter, resolver: XmlResolver | undefined): void;
    Transform(input: XPathNavigator, args: XsltArgumentList | undefined, output: TextWriter): void;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, resolver: XmlResolver | undefined): XmlReader;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined): XmlReader;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, output: TextWriter, resolver: XmlResolver | undefined): void;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, output: TextWriter): void;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, output: Stream, resolver: XmlResolver | undefined): void;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, output: Stream): void;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, output: XmlWriter, resolver: XmlResolver | undefined): void;
    Transform(input: IXPathNavigable, args: XsltArgumentList | undefined, output: XmlWriter): void;
    Transform(inputfile: string, outputfile: string, resolver: XmlResolver | undefined): void;
    Transform(inputfile: string, outputfile: string): void;
}


export const XslTransform: {
    new(): XslTransform;
};


export type XslTransform = XslTransform$instance;

export interface XsltSettings$instance {
    EnableDocumentFunction: boolean;
    EnableScript: boolean;
}


export const XsltSettings: {
    new(): XsltSettings;
    new(enableDocumentFunction: boolean, enableScript: boolean): XsltSettings;
    readonly Default: XsltSettings;
    readonly TrustedXslt: XsltSettings;
};


export type XsltSettings = XsltSettings$instance;

