// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Serialization.DataContracts
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { Dictionary_2, IEnumerable_1, List_1 } from '../System.Collections.Generic/internal/index.js';
import type { ReadOnlyCollection_1 } from '../System.Collections.ObjectModel/internal/index.js';
import type { Hashtable } from '../System.Collections/internal/index.js';
import type { ISerializationSurrogateProvider } from '../System.Runtime.Serialization/internal/index.js';
import type { XmlSchemaElement, XmlSchemaSet, XmlSchemaType } from '../System.Xml.Schema/internal/index.js';
import type { XmlDictionaryString, XmlQualifiedName } from '../System.Xml/internal/index.js';
import type { Boolean as ClrBoolean, Int32, Int64, Nullable_1, Object as ClrObject, String as ClrString, Type, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { DataContract as DataContract } from './internal/index.js';
export { DataContractSet as DataContractSet } from './internal/index.js';
export { DataMember as DataMember } from './internal/index.js';
export { XmlDataContract as XmlDataContract } from './internal/index.js';
