// Generated by tsbindgen - Architecture
// Namespace: System.Data.Common
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IEnumerable_1, IEnumerator_1, IList_1 } from '../System.Collections.Generic/internal/index.js';
import type { ReadOnlyCollection_1 } from '../System.Collections.ObjectModel/internal/index.js';
import type { ICollection, IDictionary, IDictionaryEnumerator, IEnumerable, IEnumerator, IList } from '../System.Collections/internal/index.js';
import type { AttributeCollection, Component, EventDescriptor, EventDescriptorCollection, IComponent, IContainer, ICustomTypeDescriptor, ISite, PropertyDescriptor, PropertyDescriptorCollection, TypeConverter } from '../System.ComponentModel/internal/index.js';
import type { CommandBehavior, CommandType, ConflictOption, ConnectionState, DataColumn, DataRow, DataRowVersion, DataSet, DataTable, DbType, FillErrorEventHandler, IColumnMapping, IColumnMappingCollection, IDataAdapter, IDataParameter, IDataParameterCollection, IDataReader, IDataRecord, IDbCommand, IDbConnection, IDbDataAdapter, IDbDataParameter, IDbTransaction, IsolationLevel, ITableMapping, ITableMappingCollection, LoadOption, MissingMappingAction, MissingSchemaAction, ParameterDirection, SchemaType, StateChangeEventHandler, StatementType, UpdateRowSource, UpdateStatus } from '../System.Data/internal/index.js';
import type { Stream, TextReader } from '../System.IO/internal/index.js';
import type { MethodBase } from '../System.Reflection/internal/index.js';
import type { ExternalException } from '../System.Runtime.InteropServices/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { StringBuilder } from '../System.Text/internal/index.js';
import type { Task, Task_1, ValueTask, ValueTask_1 } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Transaction } from '../System.Transactions/internal/index.js';
import type { Array as ClrArray, Attribute, Boolean as ClrBoolean, Byte, Char, DateTime, Decimal, Double, Enum, EventArgs, Exception, Guid, IAsyncDisposable, ICloneable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int16, Int32, Int64, ISpanFormattable, MarshalByRefObject, Nullable_1, Object as ClrObject, Single, String as ClrString, Type, TypeCode, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { CatalogLocation as CatalogLocation } from './internal/index.js';
export { DataAdapter as DataAdapter } from './internal/index.js';
export { DataColumnMapping as DataColumnMapping } from './internal/index.js';
export { DataColumnMappingCollection as DataColumnMappingCollection } from './internal/index.js';
export { DataTableMapping as DataTableMapping } from './internal/index.js';
export { DataTableMappingCollection as DataTableMappingCollection } from './internal/index.js';
export { DbBatch as DbBatch } from './internal/index.js';
export { DbBatchCommand as DbBatchCommand } from './internal/index.js';
export { DbBatchCommandCollection as DbBatchCommandCollection } from './internal/index.js';
export { DbColumn as DbColumn } from './internal/index.js';
export { DbCommand as DbCommand } from './internal/index.js';
export { DbCommandBuilder as DbCommandBuilder } from './internal/index.js';
export { DbConnection as DbConnection } from './internal/index.js';
export { DbConnectionStringBuilder as DbConnectionStringBuilder } from './internal/index.js';
export { DbDataAdapter as DbDataAdapter } from './internal/index.js';
export { DbDataReader as DbDataReader } from './internal/index.js';
export { DbDataReaderExtensions$instance as DbDataReaderExtensions } from './internal/index.js';
export { DbDataRecord as DbDataRecord } from './internal/index.js';
export { DbDataSource as DbDataSource } from './internal/index.js';
export { DbDataSourceEnumerator as DbDataSourceEnumerator } from './internal/index.js';
export { DbEnumerator as DbEnumerator } from './internal/index.js';
export { DbException as DbException } from './internal/index.js';
export { DbMetaDataCollectionNames$instance as DbMetaDataCollectionNames } from './internal/index.js';
export { DbMetaDataColumnNames$instance as DbMetaDataColumnNames } from './internal/index.js';
export { DbParameter as DbParameter } from './internal/index.js';
export { DbParameterCollection as DbParameterCollection } from './internal/index.js';
export { DbProviderFactory as DbProviderFactory } from './internal/index.js';
export { DbProviderFactories$instance as DbProviderFactories } from './internal/index.js';
export { DbProviderSpecificTypePropertyAttribute as DbProviderSpecificTypePropertyAttribute } from './internal/index.js';
export { DbTransaction as DbTransaction } from './internal/index.js';
export { GroupByBehavior as GroupByBehavior } from './internal/index.js';
export type IDbColumnSchemaGenerator = Internal.IDbColumnSchemaGenerator;
export { IdentifierCase as IdentifierCase } from './internal/index.js';
export { RowUpdatedEventArgs as RowUpdatedEventArgs } from './internal/index.js';
export { RowUpdatingEventArgs as RowUpdatingEventArgs } from './internal/index.js';
export { SchemaTableColumn$instance as SchemaTableColumn } from './internal/index.js';
export { SchemaTableOptionalColumn$instance as SchemaTableOptionalColumn } from './internal/index.js';
export { SupportedJoinOperators as SupportedJoinOperators } from './internal/index.js';
