// Generated by tsbindgen - Architecture
// Namespace: System.Net.ServerSentEvents
// Assembly: System.Net.ServerSentEvents

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IBufferWriter_1 } from "../../System.Buffers/internal/index.js";
import type { IAsyncEnumerable_1, IEnumerable_1 } from "../../System.Collections.Generic/internal/index.js";
import type { Stream } from "../../System.IO/internal/index.js";
import type { MethodInfo } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { Task } from "../../System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "../../System.Threading/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Action_2, AsyncCallback, Boolean as ClrBoolean, Byte, Delegate, IAsyncResult, ICloneable, Int32, IntPtr, MulticastDelegate, Nullable_1, Object as ClrObject, ReadOnlySpan_1, String as ClrString, TimeSpan, Type, ValueType, Void } from "../../System/internal/index.js";

export type SseItemParser_1<T> = (eventType: string, data: ReadOnlySpan_1<System_Internal.Byte>) => T;


export interface SseItem_1$instance<T> {
    readonly Data: T;
    EventId: string;
    readonly EventType: string;
    ReconnectionInterval: Nullable_1<TimeSpan>;
}


export const SseItem_1: {
    new<T>(data: T, eventType: string): SseItem_1$instance<T>;
};


export type SseItem_1<T> = SseItem_1$instance<T>;

export interface SseParser_1$instance<T> {
    readonly LastEventId: string;
    readonly ReconnectionInterval: TimeSpan;
    Enumerate(): IEnumerable_1<SseItem_1<T>>;
    EnumerateAsync(cancellationToken?: CancellationToken): IAsyncEnumerable_1<SseItem_1<T>>;
}


export const SseParser_1: {
    new<T>(): SseParser_1$instance<T>;
};


export type SseParser_1<T> = SseParser_1$instance<T>;

export abstract class SseFormatter$instance {
    static WriteAsync<T>(source: IAsyncEnumerable_1<SseItem_1<T>>, destination: Stream, itemFormatter: Action_2<SseItem_1<T>, IBufferWriter_1<System_Internal.Byte>>, cancellationToken?: CancellationToken): Task;
    static WriteAsync(source: IAsyncEnumerable_1<SseItem_1<System_Internal.String>>, destination: Stream, cancellationToken?: CancellationToken): Task;
}


export type SseFormatter = SseFormatter$instance;

export abstract class SseParser$instance {
    static readonly EventTypeDefault: string;
    static Create<T>(sseStream: Stream, itemParser: SseItemParser_1<T>): SseParser_1<T>;
    static Create(sseStream: Stream): SseParser_1<System_Internal.String>;
}


export type SseParser = SseParser$instance;

