// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.ConstrainedExecution
// Assembly: System.Private.CoreLib

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "../../System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode } from "../../System/internal/index.js";

export enum Cer {
    None = 0,
    MayFail = 1,
    Success = 2
}


export enum Consistency {
    MayCorruptProcess = 0,
    MayCorruptAppDomain = 1,
    MayCorruptInstance = 2,
    WillNotCorruptState = 3
}


export interface CriticalFinalizerObject$instance {
}


export const CriticalFinalizerObject: {
};


export type CriticalFinalizerObject = CriticalFinalizerObject$instance;

export interface PrePrepareMethodAttribute$instance extends Attribute {
}


export const PrePrepareMethodAttribute: {
    new(): PrePrepareMethodAttribute;
};


export type PrePrepareMethodAttribute = PrePrepareMethodAttribute$instance;

export interface ReliabilityContractAttribute$instance extends Attribute {
    readonly Cer: Cer;
    readonly ConsistencyGuarantee: Consistency;
}


export const ReliabilityContractAttribute: {
    new(consistencyGuarantee: Consistency, cer: Cer): ReliabilityContractAttribute;
};


export type ReliabilityContractAttribute = ReliabilityContractAttribute$instance;

