// Generated by tsbindgen - Architecture
// Namespace: System.Net.Http.Headers
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IEnumerable_1, IEnumerator_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, KeyValuePair_2 } from '../System.Collections.Generic/internal/index.js';
import type { IEnumerable, IEnumerator } from '../System.Collections/internal/index.js';
import type { Boolean as ClrBoolean, Byte, DateTimeOffset, Double, ICloneable, IDisposable, Int32, Int64, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan, Type, Uri, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { AuthenticationHeaderValue as AuthenticationHeaderValue } from './internal/index.js';
export { CacheControlHeaderValue as CacheControlHeaderValue } from './internal/index.js';
export { ContentDispositionHeaderValue as ContentDispositionHeaderValue } from './internal/index.js';
export { ContentRangeHeaderValue as ContentRangeHeaderValue } from './internal/index.js';
export { EntityTagHeaderValue as EntityTagHeaderValue } from './internal/index.js';
export { HeaderStringValues as HeaderStringValues } from './internal/index.js';
export { HeaderStringValues_Enumerator as HeaderStringValues_Enumerator } from './internal/index.js';
export { HttpContentHeaders as HttpContentHeaders } from './internal/index.js';
export { HttpHeaders as HttpHeaders } from './internal/index.js';
export { HttpHeadersNonValidated as HttpHeadersNonValidated } from './internal/index.js';
export { HttpHeadersNonValidated_Enumerator as HttpHeadersNonValidated_Enumerator } from './internal/index.js';
export { HttpHeaderValueCollection_1 as HttpHeaderValueCollection_1 } from './internal/index.js';
export { HttpHeaderValueCollection_1 as HttpHeaderValueCollection } from './internal/index.js';
export { HttpRequestHeaders as HttpRequestHeaders } from './internal/index.js';
export { HttpResponseHeaders as HttpResponseHeaders } from './internal/index.js';
export { MediaTypeHeaderValue as MediaTypeHeaderValue } from './internal/index.js';
export { MediaTypeWithQualityHeaderValue as MediaTypeWithQualityHeaderValue } from './internal/index.js';
export { NameValueHeaderValue as NameValueHeaderValue } from './internal/index.js';
export { NameValueWithParametersHeaderValue as NameValueWithParametersHeaderValue } from './internal/index.js';
export { ProductHeaderValue as ProductHeaderValue } from './internal/index.js';
export { ProductInfoHeaderValue as ProductInfoHeaderValue } from './internal/index.js';
export { RangeConditionHeaderValue as RangeConditionHeaderValue } from './internal/index.js';
export { RangeHeaderValue as RangeHeaderValue } from './internal/index.js';
export { RangeItemHeaderValue as RangeItemHeaderValue } from './internal/index.js';
export { RetryConditionHeaderValue as RetryConditionHeaderValue } from './internal/index.js';
export { StringWithQualityHeaderValue as StringWithQualityHeaderValue } from './internal/index.js';
export { TransferCodingHeaderValue as TransferCodingHeaderValue } from './internal/index.js';
export { TransferCodingWithQualityHeaderValue as TransferCodingWithQualityHeaderValue } from './internal/index.js';
export { ViaHeaderValue as ViaHeaderValue } from './internal/index.js';
export { WarningHeaderValue as WarningHeaderValue } from './internal/index.js';
