// Generated by tsbindgen - Architecture
// Namespace: System.Text.Encodings.Web
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { OperationStatus } from '../System.Buffers/internal/index.js';
import type { IEnumerable_1 } from '../System.Collections.Generic/internal/index.js';
import type { TextWriter } from '../System.IO/internal/index.js';
import type { UnicodeRange } from '../System.Text.Unicode/internal/index.js';
import type { Boolean as ClrBoolean, Byte, Char, Int32, Object as ClrObject, ReadOnlySpan_1, Span_1, String as ClrString, Type, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { HtmlEncoder as HtmlEncoder } from './internal/index.js';
export { JavaScriptEncoder as JavaScriptEncoder } from './internal/index.js';
export { TextEncoder as TextEncoder } from './internal/index.js';
export { TextEncoderSettings as TextEncoderSettings } from './internal/index.js';
export { UrlEncoder as UrlEncoder } from './internal/index.js';
