// Generated by tsbindgen - Architecture
// Namespace: System.Xml.XPath
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary_2, IEnumerable_1 } from '../System.Collections.Generic/internal/index.js';
import type { IComparer, IDictionary, IEnumerable, IEnumerator, IEqualityComparer } from '../System.Collections/internal/index.js';
import type { Stream, TextReader } from '../System.IO/internal/index.js';
import type { MethodBase } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { XElement, XNode } from '../System.Xml.Linq/internal/index.js';
import type { IXmlSchemaInfo, ValidationEventHandler, XmlSchemaSet, XmlSchemaType } from '../System.Xml.Schema/internal/index.js';
import type { IXmlNamespaceResolver, XmlNamespaceManager, XmlNamespaceScope, XmlNameTable, XmlNodeOrder, XmlReader, XmlSpace, XmlWriter } from '../System.Xml/internal/index.js';
import type { Boolean as ClrBoolean, DateTime, Double, Enum, Exception, ICloneable, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, SystemException, Type, TypeCode, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type IXPathNavigable = Internal.IXPathNavigable;
export { XPathDocument as XPathDocument } from './internal/index.js';
export { XPathException as XPathException } from './internal/index.js';
export { XmlSortOrder as XmlSortOrder } from './internal/index.js';
export { XmlCaseOrder as XmlCaseOrder } from './internal/index.js';
export { XmlDataType as XmlDataType } from './internal/index.js';
export { XPathResultType as XPathResultType } from './internal/index.js';
export { XPathExpression as XPathExpression } from './internal/index.js';
export { XPathItem as XPathItem } from './internal/index.js';
export { XPathNamespaceScope as XPathNamespaceScope } from './internal/index.js';
export { XPathNavigator as XPathNavigator } from './internal/index.js';
export { XPathNodeIterator as XPathNodeIterator } from './internal/index.js';
export { XPathNodeType as XPathNodeType } from './internal/index.js';
export { Extensions$instance as Extensions } from './internal/index.js';
export { XDocumentExtensions$instance as XDocumentExtensions } from './internal/index.js';
