// Generated by tsbindgen - Architecture
// Namespace: System.Net.WebSockets
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable_1, IReadOnlyDictionary_2 } from '../System.Collections.Generic/internal/index.js';
import type { NameValueCollection } from '../System.Collections.Specialized/internal/index.js';
import type { IDictionary } from '../System.Collections/internal/index.js';
import type { Win32Exception } from '../System.ComponentModel/internal/index.js';
import type { SeekOrigin, Stream } from '../System.IO/internal/index.js';
import type { HttpMessageInvoker, HttpVersionPolicy } from '../System.Net.Http/internal/index.js';
import type { RemoteCertificateValidationCallback } from '../System.Net.Security/internal/index.js';
import type { CookieCollection, CookieContainer, HttpStatusCode, ICredentials, IWebProxy } from '../System.Net/internal/index.js';
import type { MethodBase } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { X509CertificateCollection } from '../System.Security.Cryptography.X509Certificates/internal/index.js';
import type { IPrincipal } from '../System.Security.Principal/internal/index.js';
import type { Task, Task_1, ValueTask, ValueTask_1 } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { ArraySegment_1, AsyncCallback, Boolean as ClrBoolean, Byte, Enum, Exception, IAsyncDisposable, IAsyncResult, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Memory_1, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Span_1, String as ClrString, TimeSpan, Type, TypeCode, Uri, ValueType, Version, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { HttpListenerWebSocketContext as HttpListenerWebSocketContext } from './internal/index.js';
export { ValueWebSocketReceiveResult as ValueWebSocketReceiveResult } from './internal/index.js';
export { WebSocket as WebSocket } from './internal/index.js';
export { WebSocketCloseStatus as WebSocketCloseStatus } from './internal/index.js';
export { WebSocketContext as WebSocketContext } from './internal/index.js';
export { WebSocketCreationOptions as WebSocketCreationOptions } from './internal/index.js';
export { WebSocketDeflateOptions as WebSocketDeflateOptions } from './internal/index.js';
export { WebSocketError as WebSocketError } from './internal/index.js';
export { WebSocketException as WebSocketException } from './internal/index.js';
export { WebSocketMessageType as WebSocketMessageType } from './internal/index.js';
export { WebSocketMessageFlags as WebSocketMessageFlags } from './internal/index.js';
export { WebSocketReceiveResult as WebSocketReceiveResult } from './internal/index.js';
export { WebSocketState as WebSocketState } from './internal/index.js';
export { WebSocketStream as WebSocketStream } from './internal/index.js';
export { ClientWebSocket as ClientWebSocket } from './internal/index.js';
export { ClientWebSocketOptions as ClientWebSocketOptions } from './internal/index.js';
