// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Loader
// Assembly: System.Private.CoreLib

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable_1 } from "../../System.Collections.Generic/internal/index.js";
import type { Stream } from "../../System.IO/internal/index.js";
import type { Assembly, AssemblyName } from "../../System.Reflection/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Action_1, Boolean as ClrBoolean, Func_3, IDisposable, Int32, IntPtr, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "../../System/internal/index.js";

export interface AssemblyLoadContext_ContextualReflectionScope$instance {
    Dispose(): void;
}


export const AssemblyLoadContext_ContextualReflectionScope: {
    new(): AssemblyLoadContext_ContextualReflectionScope;
};


export interface __AssemblyLoadContext_ContextualReflectionScope$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export interface AssemblyLoadContext_ContextualReflectionScope$instance extends System_Internal.IDisposable$instance {}

export type AssemblyLoadContext_ContextualReflectionScope = AssemblyLoadContext_ContextualReflectionScope$instance & __AssemblyLoadContext_ContextualReflectionScope$views;


export interface AssemblyDependencyResolver$instance {
    ResolveAssemblyToPath(assemblyName: AssemblyName): string | undefined;
    ResolveUnmanagedDllToPath(unmanagedDllName: string): string | undefined;
}


export const AssemblyDependencyResolver: {
    new(componentAssemblyPath: string): AssemblyDependencyResolver;
};


export type AssemblyDependencyResolver = AssemblyDependencyResolver$instance;

export interface AssemblyLoadContext$instance {
    readonly Assemblies: IEnumerable_1<Assembly>;
    readonly IsCollectible: boolean;
    readonly Name: string;
    EnterContextualReflection(): AssemblyLoadContext_ContextualReflectionScope;
    LoadFromAssemblyName(assemblyName: AssemblyName): Assembly;
    LoadFromAssemblyPath(assemblyPath: string): Assembly;
    LoadFromNativeImagePath(nativeImagePath: string, assemblyPath: string | undefined): Assembly;
    LoadFromStream(assembly: Stream): Assembly;
    LoadFromStream(assembly: Stream, assemblySymbols: Stream | undefined): Assembly;
    SetProfileOptimizationRoot(directoryPath: string): void;
    StartProfileOptimization(profile: string | undefined): void;
    ToString(): string;
    Unload(): void;
}


export const AssemblyLoadContext: {
    new(name: string | undefined, isCollectible: boolean): AssemblyLoadContext;
    readonly Default: AssemblyLoadContext;
    readonly All: IEnumerable_1<AssemblyLoadContext>;
    readonly CurrentContextualReflectionContext: AssemblyLoadContext | undefined;
    EnterContextualReflection(activating: Assembly | undefined): AssemblyLoadContext_ContextualReflectionScope;
    GetAssemblyName(assemblyPath: string): AssemblyName;
    GetLoadContext(assembly: Assembly): AssemblyLoadContext | undefined;
};


export type AssemblyLoadContext = AssemblyLoadContext$instance;

